export const TRANSACTION_REQUEST = "TRANSACTION_REQUEST";
export const TRANSACTION_SUCCESSFULL = "TRANSACTION_SUCCESSFULL";
export const TRANSACTION_FAILED = "TRANSACTION_FAILED";

export const TRANSACTION_HISTORY_REQUEST = "TRANSACTION_HISTORY_REQUEST";
export const TRANSACTION_HISTORY_SUCCESSFULLL = "TRANSACTION_HISTORY_SUCCESSFULLL";
export const TRANSACTION_HISTORY_FAILED = "TRANSACTION_HISTORY_FAILED";
